# Module 2 - Lectures

Starting with **Loading Data** [lecture](https://courses.edx.org/courses/course-v1:Microsoft+DAT210x+4T2017/courseware/b7aa9093-0ee1-9e62-4188-6f9d25a2ce85/109598e7-56e4-2f20-99a1-f61f7c6dd93d/?child=first).

In [46]:
import pandas as pd

Different read methods take different arguments and work differently.

(Sample JSON [website](http://jsonstudio.com/resources/))

In [28]:
df1 = pd.read_excel('Module2 - Lab1.xls', 'Features')
df2 = pd.read_json('~/Downloads/world_bank.json', orient='columns', lines=True)
dfs = pd.read_html('https://www.textfixer.com/tutorials/css-tables.php')

In [29]:
len(dfs)

4

In [30]:
dfsub1 = dfs[0]

In [31]:
dfsub1

               0              1              2
0  Info Header 1  Info Header 2  Info Header 3
1        Text 1A        Text 1B        Text 1C
2        Text 2A        Text 2B        Text 2C

This may not work with current setup.

In [ ]:
# # Doesn't work with current setup - Not worth it to debug at this time
# from sqlalchemy import create_engine
# engine = create_engine('sqlite:///:memory:')
# df = pd.read_sql_table('my_table', engine, columns=['ColA', 'ColB'])

In [33]:
df = pd.read_csv('Datasets/tutorial.csv', sep=',')

In [34]:
df

       col0      col1      col2      col3
0 -0.722876 -1.330682  1.309208  0.232378
1  1.160396 -0.730879  0.677368  1.044722
2 -1.062870 -0.503704 -0.238536 -1.417937
3  0.437078  0.362640 -0.111228 -1.649853

In [35]:
len(df.columns)

4

In [36]:
df.columns = ['new', 'column', 'header', 'labels']

In [37]:
df

        new    column    header    labels
0 -0.722876 -1.330682  1.309208  0.232378
1  1.160396 -0.730879  0.677368  1.044722
2 -1.062870 -0.503704 -0.238536 -1.417937
3  0.437078  0.362640 -0.111228 -1.649853

In [42]:
df2.head(7)

,_id,approvalfy,board_approval_month,boardapprovaldate,borrower,closingdate,country_namecode,countrycode,countryname,countryshortname,...,sectorcode,source,status,supplementprojectflg,theme1,theme_namecode,themecode,totalamt,totalcommamt,url
0,{'$oid': '52b213b38594d8a2be17c780'},1999,November,2013-11-12T00:00:00Z,FEDERAL DEMOCRATIC REPUBLIC OF ETHIOPIA,2018-07-07T00:00:00Z,Federal Democratic Republic of Ethiopia!$!ET,ET,Federal Democratic Republic of Ethiopia,Ethiopia,...,"ET,BS,ES,EP",IBRD,Active,N,"{'Name': 'Education for all', 'Percent': 100}","[{'name': 'Education for all', 'code': '65'}]",65,130000000,130000000,http://www.worldbank.org/projects/P129828/ethi...
1,{'$oid': '52b213b38594d8a2be17c781'},2015,November,2013-11-04T00:00:00Z,GOVERNMENT OF TUNISIA,NaN,Republic of Tunisia!$!TN,TN,Republic of Tunisia,Tunisia,...,"BZ,BS",IBRD,Active,N,"{'Name': 'Other economic management', 'Percent...","[{'name': 'Other economic management', 'code':...","54,24",0,4700000,http://www.worldbank.org/projects/P144674?lang=en
2,{'$oid': '52b213b38594d8a2be17c782'},2014,November,2013-11-01T00:00:00Z,MINISTRY OF FINANCE AND ECONOMIC DEVEL,NaN,Tuvalu!$!TV,TV,Tuvalu,Tuvalu,...,TI,IBRD,Active,Y,"{'Name': 'Regional integration', 'Percent': 46}","[{'name': 'Regional integration', 'code': '47'...","52,81,25,47",6060000,6060000,http://www.worldbank.org/projects/P145310?lang=en
3,{'$oid': '52b213b38594d8a2be17c783'},2014,October,2013-10-31T00:00:00Z,MIN. OF PLANNING AND INT'L COOPERATION,NaN,Republic of Yemen!$!RY,RY,Republic of Yemen,"Yemen, Republic of",...,JB,IBRD,Active,N,"{'Name': 'Participation and civic engagement',...",[{'name': 'Participation and civic engagement'...,"59,57",0,1500000,http://www.worldbank.org/projects/P144665?lang=en
4,{'$oid': '52b213b38594d8a2be17c784'},2014,October,2013-10-31T00:00:00Z,MINISTRY OF FINANCE,2019-04-30T00:00:00Z,Kingdom of Lesotho!$!LS,LS,Kingdom of Lesotho,Lesotho,...,"FH,YW,YZ",IBRD,Active,N,{'Name': 'Export development and competitivene...,[{'name': 'Export development and competitiven...,"41,45",13100000,13100000,http://www.worldbank.org/projects/P144933/seco...
5,{'$oid': '52b213b38594d8a2be17c785'},2014,October,2013-10-31T00:00:00Z,REPUBLIC OF KENYA,NaN,Republic of Kenya!$!KE,KE,Republic of Kenya,Kenya,...,JB,IBRD,Active,Y,"{'Name': 'Social safety nets', 'Percent': 100}","[{'name': 'Social safety nets', 'code': '54'}]",54,10000000,10000000,http://www.worldbank.org/projects/P146161?lang=en
6,{'$oid': '52b213b38594d8a2be17c786'},2014,October,2013-10-29T00:00:00Z,GOVERNMENT OF INDIA,2019-06-30T00:00:00Z,Republic of India!$!IN,IN,Republic of India,India,...,TI,IBRD,Active,N,{'Name': 'Administrative and civil service ref...,[{'name': 'Administrative and civil service re...,"39,25",500000000,500000000,http://www.worldbank.org/projects/P121185/firs...

In [39]:
df2.tail()

,_id,approvalfy,board_approval_month,boardapprovaldate,borrower,closingdate,country_namecode,countrycode,countryname,countryshortname,...,sectorcode,source,status,supplementprojectflg,theme1,theme_namecode,themecode,totalamt,totalcommamt,url
495,{'$oid': '52b213b38594d8a2be17c96f'},2013,August,2012-08-10T00:00:00Z,THE COMPETITIVENESS COMPANY,2013-08-31T00:00:00Z,Jamaica!$!JM,JM,Jamaica,Jamaica,...,"EV,AZ",IBRD,Closed,N,"{'Name': 'Regulation and competition policy', ...","[{'name': 'Regulation and competition policy',...","62,40",0,50000,http://www.worldbank.org/projects/P127299/tech...
496,{'$oid': '52b213b38594d8a2be17c970'},2013,August,2012-08-09T00:00:00Z,LAO PEOPLES DEMOCRATIC REPUBLIC,2012-12-31T00:00:00Z,Lao People's Democratic Republic!$!LA,LA,Lao People's Democratic Republic,Lao People's Democratic Republic,...,"YZ,JA,EZ,FZ,BC",IBRD,Closed,N,"{'Name': 'Child health', 'Percent': 14}","[{'name': 'Child health', 'code': '63'}, {'nam...","65,27,49,63",20000000,20000000,http://www.worldbank.org/projects/P125298/lao-...
497,{'$oid': '52b213b38594d8a2be17c971'},2013,August,2012-08-03T00:00:00Z,GOVERNMENT OF THE REPUBLIC OF GUINEA,2014-12-31T00:00:00Z,Republic of Guinea!$!GN,GN,Republic of Guinea,Guinea,...,"AB,AH,AI",IBRD,Active,N,"{'Name': 'Global food crisis response', 'Perce...","[{'name': 'Global food crisis response', 'code...",91,0,20000000,http://www.worldbank.org/projects/P128309/seco...
498,{'$oid': '52b213b38594d8a2be17c972'},2013,August,2012-08-02T00:00:00Z,REPUBLIC OF INDONESIA,2017-09-30T00:00:00Z,Republic of Indonesia!$!ID,ID,Republic of Indonesia,Indonesia,...,"YA,BL,AB",IBRD,Active,N,"{'Name': 'Rural services and infrastructure', ...","[{'name': 'Rural services and infrastructure',...","77,91,78",80000000,80000000,http://www.worldbank.org/projects/P117243/sust...
499,{'$oid': '52b213b38594d8a2be17c973'},2013,August,2012-08-02T00:00:00Z,GOVERMENT OF KENYA,2018-12-31T00:00:00Z,Republic of Kenya!$!KE,KE,Republic of Kenya,Kenya,...,"BV,TC",IBRD,Active,N,{'Name': 'Municipal governance and institution...,[{'name': 'Municipal governance and institutio...,"39,49,88,73",300000000,300000000,http://www.worldbank.org/projects/P126321/keny...

In [40]:
df.describe()

            new    column    header    labels
count  4.000000  4.000000  4.000000  4.000000
mean  -0.047068 -0.550656  0.409203 -0.447672
std    1.029715  0.701720  0.723956  1.300815
min   -1.062870 -1.330682 -0.238536 -1.649853
25%   -0.807875 -0.880830 -0.143055 -1.475916
50%   -0.142899 -0.617291  0.283070 -0.592780
75%    0.617907 -0.287118  0.835328  0.435464
max    1.160396  0.362640  1.309208  1.044722

In [41]:
df2.index

Int64Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
            ...
            490, 491, 492, 493, 494, 495, 496, 497, 498, 499],
           dtype='int64', length=500)

In [43]:
df2.dtypes

_id                         object
approvalfy                   int64
board_approval_month        object
boardapprovaldate           object
borrower                    object
closingdate                 object
country_namecode            object
countrycode                 object
countryname                 object
countryshortname            object
docty                       object
envassesmentcategorycode    object
grantamt                     int64
ibrdcommamt                  int64
id                          object
idacommamt                   int64
impagency                   object
lendinginstr                object
lendinginstrtype            object
lendprojectcost              int64
majorsector_percent         object
mjsector_namecode           object
mjtheme                     object
mjtheme_namecode            object
mjthemecode                 object
prodline                    object
prodlinetext                object
productlinetype             object
project_abstract            object
project_name                object
projectdocs                 object
projectfinancialtype        object
projectstatusdisplay        object
regionname                  object
sector                      object
sector1                     object
sector2                     object
sector3                     object
sector4                     object
sector_namecode             object
sectorcode                  object
source                      object
status                      object
supplementprojectflg        object
theme1                      object
theme_namecode              object
themecode                   object
totalamt                     int64
totalcommamt                 int64
url                         object
dtype: object

# Next section
Moving on to **Slicin** section, which is about indexing, and uses a provided csv file for working on.

In [44]:
# This command resets the variable space. Uncomment, then run. Notebook will ask for confirmation.
# %reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y

In [47]:
df = pd.read_csv('Datasets/direct_marketing.csv')
df

,recency,history_segment,history,mens,womens,zip_code,newbie,channel,segment,visit,conversion,spend,DM_category
0,10,2) $100 - $200,142.44,1,0,Surburban,0,Phone,Womens E-Mail,0,0,0.0,4
1,6,3) $200 - $350,329.08,1,1,Rural,1,Web,No E-Mail,0,0,0.0,11
2,7,2) $100 - $200,180.65,0,1,Surburban,1,Web,Womens E-Mail,0,0,0.0,1
3,9,5) $500 - $750,675.83,1,0,Rural,1,Web,Mens E-Mail,0,0,0.0,2
4,2,1) $0 - $100,45.34,1,0,Urban,0,Web,Womens E-Mail,0,0,0.0,4
5,6,2) $100 - $200,134.83,0,1,Surburban,0,Phone,Womens E-Mail,1,0,0.0,1
6,9,3) $200 - $350,280.20,1,0,Surburban,1,Phone,Womens E-Mail,0,0,0.0,4
7,9,1) $0 - $100,46.42,0,1,Urban,0,Phone,Womens E-Mail,0,0,0.0,1
8,9,5) $500 - $750,675.07,1,1,Rural,1,Phone,Mens E-Mail,0,0,0.0,5
9,10,1) $0 - $100,32.84,0,1,Urban,1,Web,Womens E-Mail,0,0,0.0,1
10,7,5) $500 - $750,548.91,0,1,Urban,1,Phone,Womens E-Mail,1,0,0.0,1
11,1,3) $200 - $350,211.45,0,1,Urban,1,Phone,Womens E-Mail,0,0,0.0,1
12,5,5) $500 - $750,642.90,0,1,Surburban,1,Multichannel,Womens E-Mail,0,0,0.0,1
13,2,2) $100 - $200,101.64,0,1,Urban,0,Web,Mens E-Mail,1,0,0.0,3
14,4,3) $200 - $350,241.42,0,1,Rural,1,Multichannel,No E-Mail,0,0,0.0,5
15,3,1) $0 - $100,58.13,1,0,Urban,1,Web,No E-Mail,1,0,0.0,6
16,5,1) $0 - $100,29.99,1,0,Surburban,0,Phone,Mens E-Mail,0,0,0.0,2
17,9,2) $100 - $200,112.35,1,0,Rural,0,Web,Mens E-Mail,0,0,0.0,2
18,11,3) $200 - $350,219.04,1,1,Surburban,0,Phone,Mens E-Mail,0,0,0.0,5
19,5,"6) $750 - $1,000",828.42,1,0,Surburban,1,Multichannel,Mens E-Mail,0,0,0.0,2
20,9,1) $0 - $100,29.99,0,1,Surburban,1,Phone,No E-Mail,0,0,0.0,5
21,11,2) $100 - $200,182.32,1,0,Surburban,0,Phone,Mens E-Mail,0,0,0.0,2
22,2,2) $100 - $200,118.40,1,0,Surburban,0,Web,Mens E-Mail,1,0,0.0,2
23,2,1) $0 - $100,29.99,0,1,Urban,1,Phone,No E-Mail,0,0,0.0,5
24,4,1) $0 - $100,78.24,1,0,Surburban,0,Web,No E-Mail,0,0,0.0,6
25,6,2) $100 - $200,139.87,0,1,Rural,1,Web,Mens E-Mail,0,0,0.0,3
26,12,2) $100 - $200,115.39,0,1,Surburban,0,Phone,Mens E-Mail,1,0,0.0,3
27,6,2) $100 - $200,162.98,0,1,Surburban,0,Web,Mens E-Mail,0,0,0.0,3
28,7,4) $350 - $500,435.73,0,1,Urban,1,Web,No E-Mail,0,0,0.0,5
29,2,3) $200 - $350,203.35,1,0,Rural,0,Web,No E-Mail,0,0,0.0,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
63970,4,2) $100 - $200,191.15,0,1,Surburban,1,Web,Womens E-Mail,0,0,0.0,1
63971,5,5) $500 - $750,549.87,0,1,Surburban,1,Phone,Womens E-Mail,0,0,0.0,1
63972,3,5) $500 - $750,554.97,0,1,Surburban,1,Web,No E-Mail,0,0,0.0,5
63973,8,4) $350 - $500,471.80,1,0,Surburban,1,Multichannel,Womens E-Mail,0,0,0.0,4
63974,8,1) $0 - $100,73.65,0,1,Surburban,0,Phone,Mens E-Mail,0,0,0.0,3
63975,10,"6) $750 - $1,000",883.92,1,0,Urban,1,Phone,No E-Mail,0,0,0.0,6
63976,1,5) $500 - $750,710.72,1,1,Urban,1,Phone,No E-Mail,0,0,0.0,11
63977,8,1) $0 - $100,29.99,0,1,Surburban,0,Web,No E-Mail,1,0,0.0,5
63978,10,2) $100 - $200,102.01,0,1,Urban,1,Phone,Mens E-Mail,0,0,0.0,3
63979,10,2) $100 - $200,168.21,0,1,Surburban,0,Phone,No E-Mail,0,0,0.0,5
63980,3,4) $350 - $500,487.10,0,1,Surburban,1,Phone,No E-Mail,0,0,0.0,5
63981,4,2) $100 - $200,125.53,0,1,Rural,1,Phone,No E-Mail,0,0,0.0,5
63982,5,1) $0 - $100,29.99,1,0,Urban,1,Phone,Mens E-Mail,0,0,0.0,2
63983,2,1) $0 - $100,83.03,0,1,Urban,0,Phone,No E-Mail,0,0,0.0,5
63984,2,3) $200 - $350,209.51,0,1,Urban,1,Web,Womens E-Mail,0,0,0.0,1
63985,9,1) $0 - $100,29.99,1,0,Urban,0,Phone,Mens E-Mail,1,0,0.0,2
63986,9,1) $0 - $100,35.26,0,1,Urban,1,Web,Womens E-Mail,0,0,0.0,1
63987,1,1) $0 - $100,79.70,1,0,Surburban,1,Web,No E-Mail,0,0,0.0,6
63988,6,1) $0 - $100,32.98,1,0,Surburban,0,Web,Mens E-Mail,0,0,0.0,2
63989,10,3) $200 - $350,304.30,1,1,Surburban,0,Web,Womens E-Mail,1,0,0.0,5
63990,6,1) $0 - $100,80.02,0,1,Surburban,0,Phone,No E-Mail,0,0,0.0,5
63991,1,3) $200 - $350,306.10,1,0,Surburban,1,Phone,Womens E-Mail,0,0,0.0,4
63992,1,5) $500 - $750,519.69,1,1,Urban,1,Phone,Mens E-Mail,0,0,0.0,5
63993,4,4) $350 - $500,374.07,0,1,Surburban,0,Phone,Womens E-Mail,0,0,0.0,1
63994,7,1) $0 - $100,86.46,0,1,Urban,0,Web,Mens E-Mail,0,0,0.0,3
63995,10,2) $100 - $200,105.54,1,0,Urban,0,Web,Mens E-Mail,0,0,0.0,2
63996,5,1) $0 - $100,38.91,0,1,Urban,1,Phone,Mens E-Mail,0,0,0.0,3
63997,6,1) $0 - $100,29.99,1,0,Urban,1,Phone,Mens E-Mail,0,0,0.0,2
63998,1,5) $500 - $750,552.94,1,0,Surburban,1,Multichannel,Womens E-Mail,0,0,0.0,4
63999,1,4) $350 - $500,472.82,0,1,Surburban,0,Web,Mens E-Mail,0,0,0.0,3

In [48]:
df.recency
df['recency']
df[['recency']]
df.loc[:, 'recency']
df.loc[:, ['recency']]
df.iloc[:, 0]
df.iloc[:, [0]]

       recency
0           10
1            6
2            7
3            9
4            2
5            6
6            9
7            9
8            9
9           10
10           7
11           1
12           5
13           2
14           4
15           3
16           5
17           9
18          11
19           5
20           9
21          11
22           2
23           2
24           4
25           6
26          12
27           6
28           7
29           2
...        ...
63970        4
63971        5
63972        3
63973        8
63974        8
63975       10
63976        1
63977        8
63978       10
63979       10
63980        3
63981        4
63982        5
63983        2
63984        2
63985        9
63986        9
63987        1
63988        6
63989       10
63990        6
63991        1
63992        1
63993        4
63994        7
63995       10
63996        5
63997        6
63998        1
63999        1

[64000 rows x 1 columns]

In [49]:
# These return a series object (equivalent output)
df.recency
df['recency']
df.loc[:, 'recency']
df.iloc[:, 0]

0        10
1         6
2         7
3         9
4         2
5         6
6         9
7         9
8         9
9        10
10        7
11        1
12        5
13        2
14        4
15        3
16        5
17        9
18       11
19        5
20        9
21       11
22        2
23        2
24        4
25        6
26       12
27        6
28        7
29        2
         ..
63970     4
63971     5
63972     3
63973     8
63974     8
63975    10
63976     1
63977     8
63978    10
63979    10
63980     3
63981     4
63982     5
63983     2
63984     2
63985     9
63986     9
63987     1
63988     6
63989    10
63990     6
63991     1
63992     1
63993     4
63994     7
63995    10
63996     5
63997     6
63998     1
63999     1
Name: recency, Length: 64000, dtype: int64

In [50]:
# These return a dataframe (equivalent output)
df[['recency']]
df.loc[:, ['recency']]
df.iloc[:, [0]]

       recency
0           10
1            6
2            7
3            9
4            2
5            6
6            9
7            9
8            9
9           10
10           7
11           1
12           5
13           2
14           4
15           3
16           5
17           9
18          11
19           5
20           9
21          11
22           2
23           2
24           4
25           6
26          12
27           6
28           7
29           2
...        ...
63970        4
63971        5
63972        3
63973        8
63974        8
63975       10
63976        1
63977        8
63978       10
63979       10
63980        3
63981        4
63982        5
63983        2
63984        2
63985        9
63986        9
63987        1
63988        6
63989       10
63990        6
63991        1
63992        1
63993        4
63994        7
63995       10
63996        5
63997        6
63998        1
63999        1

[64000 rows x 1 columns]

In [51]:
df[0:2]
df.iloc[0:2, :]

,recency,history_segment,history,mens,womens,zip_code,newbie,channel,segment,visit,conversion,spend,DM_category
0,10,2) $100 - $200,142.44,1,0,Surburban,0,Phone,Womens E-Mail,0,0,0.0,4
1,6,3) $200 - $350,329.08,1,1,Rural,1,Web,No E-Mail,0,0,0.0,11

# Next section
Moving on to **Boolean Indexing** section, which is about indexing using boolean operators and comparisons.

In [54]:
df.recency < 7

0        False
1         True
2        False
3        False
4         True
5         True
6        False
7        False
8        False
9        False
10       False
11        True
12        True
13        True
14        True
15        True
16        True
17       False
18       False
19        True
20       False
21       False
22        True
23        True
24        True
25        True
26       False
27        True
28       False
29        True
         ...
63970     True
63971     True
63972     True
63973    False
63974    False
63975    False
63976     True
63977    False
63978    False
63979    False
63980     True
63981     True
63982     True
63983     True
63984     True
63985    False
63986    False
63987     True
63988     True
63989    False
63990     True
63991     True
63992     True
63993     True
63994    False
63995    False
63996     True
63997     True
63998     True
63999     True
Name: recency, Length: 64000, dtype: bool

In [55]:
df[df.recency < 7]

,recency,history_segment,history,mens,womens,zip_code,newbie,channel,segment,visit,conversion,spend,DM_category
1,6,3) $200 - $350,329.08,1,1,Rural,1,Web,No E-Mail,0,0,0.0,11
4,2,1) $0 - $100,45.34,1,0,Urban,0,Web,Womens E-Mail,0,0,0.0,4
5,6,2) $100 - $200,134.83,0,1,Surburban,0,Phone,Womens E-Mail,1,0,0.0,1
11,1,3) $200 - $350,211.45,0,1,Urban,1,Phone,Womens E-Mail,0,0,0.0,1
12,5,5) $500 - $750,642.90,0,1,Surburban,1,Multichannel,Womens E-Mail,0,0,0.0,1
13,2,2) $100 - $200,101.64,0,1,Urban,0,Web,Mens E-Mail,1,0,0.0,3
14,4,3) $200 - $350,241.42,0,1,Rural,1,Multichannel,No E-Mail,0,0,0.0,5
15,3,1) $0 - $100,58.13,1,0,Urban,1,Web,No E-Mail,1,0,0.0,6
16,5,1) $0 - $100,29.99,1,0,Surburban,0,Phone,Mens E-Mail,0,0,0.0,2
19,5,"6) $750 - $1,000",828.42,1,0,Surburban,1,Multichannel,Mens E-Mail,0,0,0.0,2
22,2,2) $100 - $200,118.40,1,0,Surburban,0,Web,Mens E-Mail,1,0,0.0,2
23,2,1) $0 - $100,29.99,0,1,Urban,1,Phone,No E-Mail,0,0,0.0,5
24,4,1) $0 - $100,78.24,1,0,Surburban,0,Web,No E-Mail,0,0,0.0,6
25,6,2) $100 - $200,139.87,0,1,Rural,1,Web,Mens E-Mail,0,0,0.0,3
27,6,2) $100 - $200,162.98,0,1,Surburban,0,Web,Mens E-Mail,0,0,0.0,3
29,2,3) $200 - $350,203.35,1,0,Rural,0,Web,No E-Mail,0,0,0.0,6
30,2,3) $200 - $350,237.53,0,1,Surburban,0,Phone,Womens E-Mail,0,0,0.0,1
32,6,2) $100 - $200,128.01,0,1,Urban,0,Web,Mens E-Mail,0,0,0.0,3
34,3,1) $0 - $100,29.99,1,0,Rural,0,Web,Womens E-Mail,0,0,0.0,4
35,4,3) $200 - $350,218.72,0,1,Urban,0,Multichannel,Womens E-Mail,0,0,0.0,1
36,1,5) $500 - $750,514.52,0,1,Surburban,1,Web,Mens E-Mail,0,0,0.0,3
37,4,"6) $750 - $1,000",766.47,1,1,Urban,1,Multichannel,Mens E-Mail,0,0,0.0,5
41,3,1) $0 - $100,99.23,1,0,Rural,0,Web,Mens E-Mail,1,0,0.0,2
43,2,4) $350 - $500,492.02,1,0,Surburban,0,Phone,No E-Mail,0,0,0.0,6
44,1,1) $0 - $100,48.32,0,1,Urban,0,Web,No E-Mail,0,0,0.0,5
46,2,4) $350 - $500,391.33,1,0,Surburban,0,Web,No E-Mail,0,0,0.0,6
47,1,5) $500 - $750,729.70,1,1,Surburban,1,Web,Mens E-Mail,0,0,0.0,5
48,3,2) $100 - $200,134.59,1,0,Urban,1,Phone,Womens E-Mail,1,0,0.0,4
50,3,3) $200 - $350,203.30,0,1,Surburban,0,Web,No E-Mail,0,0,0.0,5
55,6,1) $0 - $100,42.66,1,0,Surburban,0,Web,No E-Mail,0,0,0.0,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
63949,5,1) $0 - $100,86.79,1,0,Rural,0,Phone,No E-Mail,0,0,0.0,6
63950,1,1) $0 - $100,45.67,0,1,Surburban,1,Web,Mens E-Mail,0,0,0.0,3
63953,5,2) $100 - $200,166.24,0,1,Urban,0,Phone,No E-Mail,0,0,0.0,5
63954,2,1) $0 - $100,93.97,1,0,Urban,0,Web,No E-Mail,1,0,0.0,6
63955,1,1) $0 - $100,29.99,1,0,Surburban,0,Phone,Mens E-Mail,0,0,0.0,2
63960,1,3) $200 - $350,221.89,0,1,Surburban,1,Multichannel,No E-Mail,0,0,0.0,5
63961,4,3) $200 - $350,337.36,1,0,Urban,0,Web,Mens E-Mail,1,0,0.0,2
63964,2,"6) $750 - $1,000",772.99,1,1,Surburban,1,Web,Mens E-Mail,0,0,0.0,5
63966,4,2) $100 - $200,170.03,1,0,Surburban,0,Web,Womens E-Mail,0,0,0.0,4
63967,5,1) $0 - $100,77.73,0,1,Urban,1,Phone,No E-Mail,0,0,0.0,5
63969,3,1) $0 - $100,67.78,0,1,Surburban,0,Web,Womens E-Mail,0,0,0.0,1
63970,4,2) $100 - $200,191.15,0,1,Surburban,1,Web,Womens E-Mail,0,0,0.0,1
63971,5,5) $500 - $750,549.87,0,1,Surburban,1,Phone,Womens E-Mail,0,0,0.0,1
63972,3,5) $500 - $750,554.97,0,1,Surburban,1,Web,No E-Mail,0,0,0.0,5
63976,1,5) $500 - $750,710.72,1,1,Urban,1,Phone,No E-Mail,0,0,0.0,11
63980,3,4) $350 - $500,487.10,0,1,Surburban,1,Phone,No E-Mail,0,0,0.0,5
63981,4,2) $100 - $200,125.53,0,1,Rural,1,Phone,No E-Mail,0,0,0.0,5
63982,5,1) $0 - $100,29.99,1,0,Urban,1,Phone,Mens E-Mail,0,0,0.0,2
63983,2,1) $0 - $100,83.03,0,1,Urban,0,Phone,No E-Mail,0,0,0.0,5
63984,2,3) $200 - $350,209.51,0,1,Urban,1,Web,Womens E-Mail,0,0,0.0,1
63987,1,1) $0 - $100,79.70,1,0,Surburban,1,Web,No E-Mail,0,0,0.0,6
63988,6,1) $0 - $100,32.98,1,0,Surburban,0,Web,Mens E-Mail,0,0,0.0,2
63990,6,1) $0 - $100,80.02,0,1,Surburban,0,Phone,No E-Mail,0,0,0.0,5
63991,1,3) $200 - $350,306.10,1,0,Surburban,1,Phone,Womens E-Mail,0,0,0.0,4
63992,1,5) $500 - $750,519.69,1,1,Urban,1,Phone,Mens E-Mail,0,0,0.0,5
63993,4,4) $350 - $500,374.07,0,1,Surburban,0,Phone,Womens E-Mail,0,0,0.0,1
63996,5,1) $0 - $100,38.91,0,1,Urban,1,Phone,Mens E-Mail,0,0,0.0,3
63997,6,1) $0 - $100,29.99,1,0,Urban,1,Phone,Mens E-Mail,0,0,0.0,2
63998,1,5) $500 - $750,552.94,1,0,Surburban,1,Multichannel,Womens E-Mail,0,0,0.0,4
63999,1,4) $350 - $500,472.82,0,1,Surburban,0,Web,Mens E-Mail,0,0,0.0,3

In [56]:
df[ (df.recency < 7) & (df.newbie == 0) ]

,recency,history_segment,history,mens,womens,zip_code,newbie,channel,segment,visit,conversion,spend,DM_category
4,2,1) $0 - $100,45.34,1,0,Urban,0,Web,Womens E-Mail,0,0,0.0,4
5,6,2) $100 - $200,134.83,0,1,Surburban,0,Phone,Womens E-Mail,1,0,0.0,1
13,2,2) $100 - $200,101.64,0,1,Urban,0,Web,Mens E-Mail,1,0,0.0,3
16,5,1) $0 - $100,29.99,1,0,Surburban,0,Phone,Mens E-Mail,0,0,0.0,2
22,2,2) $100 - $200,118.40,1,0,Surburban,0,Web,Mens E-Mail,1,0,0.0,2
24,4,1) $0 - $100,78.24,1,0,Surburban,0,Web,No E-Mail,0,0,0.0,6
27,6,2) $100 - $200,162.98,0,1,Surburban,0,Web,Mens E-Mail,0,0,0.0,3
29,2,3) $200 - $350,203.35,1,0,Rural,0,Web,No E-Mail,0,0,0.0,6
30,2,3) $200 - $350,237.53,0,1,Surburban,0,Phone,Womens E-Mail,0,0,0.0,1
32,6,2) $100 - $200,128.01,0,1,Urban,0,Web,Mens E-Mail,0,0,0.0,3
34,3,1) $0 - $100,29.99,1,0,Rural,0,Web,Womens E-Mail,0,0,0.0,4
35,4,3) $200 - $350,218.72,0,1,Urban,0,Multichannel,Womens E-Mail,0,0,0.0,1
41,3,1) $0 - $100,99.23,1,0,Rural,0,Web,Mens E-Mail,1,0,0.0,2
43,2,4) $350 - $500,492.02,1,0,Surburban,0,Phone,No E-Mail,0,0,0.0,6
44,1,1) $0 - $100,48.32,0,1,Urban,0,Web,No E-Mail,0,0,0.0,5
46,2,4) $350 - $500,391.33,1,0,Surburban,0,Web,No E-Mail,0,0,0.0,6
50,3,3) $200 - $350,203.30,0,1,Surburban,0,Web,No E-Mail,0,0,0.0,5
55,6,1) $0 - $100,42.66,1,0,Surburban,0,Web,No E-Mail,0,0,0.0,6
59,3,2) $100 - $200,143.93,0,1,Surburban,0,Phone,Womens E-Mail,0,0,0.0,1
61,2,1) $0 - $100,96.91,1,0,Surburban,0,Phone,Womens E-Mail,0,0,0.0,4
65,5,3) $200 - $350,222.07,0,1,Surburban,0,Phone,Womens E-Mail,0,0,0.0,1
70,2,3) $200 - $350,278.80,1,0,Rural,0,Web,Mens E-Mail,0,0,0.0,2
72,2,4) $350 - $500,428.74,1,0,Rural,0,Phone,Mens E-Mail,0,0,0.0,2
76,4,2) $100 - $200,194.11,1,0,Urban,0,Phone,No E-Mail,0,0,0.0,6
79,2,1) $0 - $100,29.99,0,1,Surburban,0,Phone,Mens E-Mail,0,0,0.0,3
81,2,1) $0 - $100,95.33,0,1,Surburban,0,Web,No E-Mail,1,0,0.0,5
86,2,1) $0 - $100,82.59,1,0,Surburban,0,Phone,Womens E-Mail,0,0,0.0,4
87,6,2) $100 - $200,165.77,0,1,Urban,0,Web,Womens E-Mail,1,0,0.0,1
95,3,2) $100 - $200,133.51,1,0,Urban,0,Web,Mens E-Mail,0,0,0.0,2
97,1,1) $0 - $100,47.44,0,1,Urban,0,Phone,Womens E-Mail,0,0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
63890,2,3) $200 - $350,229.79,1,1,Urban,0,Phone,Mens E-Mail,1,0,0.0,5
63891,4,1) $0 - $100,65.23,0,1,Urban,0,Phone,Womens E-Mail,0,0,0.0,1
63893,2,3) $200 - $350,288.30,1,1,Surburban,0,Phone,Womens E-Mail,0,0,0.0,5
63901,4,2) $100 - $200,158.91,1,0,Surburban,0,Web,No E-Mail,0,0,0.0,6
63902,3,3) $200 - $350,309.39,1,1,Urban,0,Phone,Womens E-Mail,0,0,0.0,5
63904,1,1) $0 - $100,29.99,0,1,Surburban,0,Web,Womens E-Mail,1,0,0.0,1
63906,4,3) $200 - $350,311.63,0,1,Urban,0,Multichannel,No E-Mail,0,0,0.0,5
63910,6,1) $0 - $100,29.99,1,0,Surburban,0,Phone,Mens E-Mail,0,0,0.0,2
63911,5,4) $350 - $500,373.13,0,1,Urban,0,Phone,Womens E-Mail,0,0,0.0,1
63915,4,3) $200 - $350,300.90,1,0,Surburban,0,Phone,No E-Mail,0,0,0.0,6
63916,6,1) $0 - $100,34.50,1,0,Urban,0,Phone,Womens E-Mail,0,0,0.0,4
63918,3,1) $0 - $100,29.99,1,0,Surburban,0,Web,No E-Mail,0,0,0.0,6
63919,3,2) $100 - $200,149.96,1,0,Urban,0,Web,Womens E-Mail,0,0,0.0,4
63924,4,2) $100 - $200,101.40,0,1,Urban,0,Web,No E-Mail,0,0,0.0,5
63931,2,1) $0 - $100,29.99,1,0,Surburban,0,Web,No E-Mail,0,0,0.0,6
63932,1,4) $350 - $500,426.36,1,1,Surburban,0,Multichannel,Mens E-Mail,1,0,0.0,5
63935,4,4) $350 - $500,353.47,1,1,Urban,0,Multichannel,Mens E-Mail,0,0,0.0,5
63941,2,2) $100 - $200,130.96,1,0,Urban,0,Phone,Mens E-Mail,0,0,0.0,2
63949,5,1) $0 - $100,86.79,1,0,Rural,0,Phone,No E-Mail,0,0,0.0,6
63953,5,2) $100 - $200,166.24,0,1,Urban,0,Phone,No E-Mail,0,0,0.0,5
63954,2,1) $0 - $100,93.97,1,0,Urban,0,Web,No E-Mail,1,0,0.0,6
63955,1,1) $0 - $100,29.99,1,0,Surburban,0,Phone,Mens E-Mail,0,0,0.0,2
63961,4,3) $200 - $350,337.36,1,0,Urban,0,Web,Mens E-Mail,1,0,0.0,2
63966,4,2) $100 - $200,170.03,1,0,Surburban,0,Web,Womens E-Mail,0,0,0.0,4
63969,3,1) $0 - $100,67.78,0,1,Surburban,0,Web,Womens E-Mail,0,0,0.0,1
63983,2,1) $0 - $100,83.03,0,1,Urban,0,Phone,No E-Mail,0,0,0.0,5
63988,6,1) $0 - $100,32.98,1,0,Surburban,0,Web,Mens E-Mail,0,0,0.0,2
63990,6,1) $0 - $100,80.02,0,1,Surburban,0,Phone,No E-Mail,0,0,0.0,5
63993,4,4) $350 - $500,374.07,0,1,Surburban,0,Phone,Womens E-Mail,0,0,0.0,1
63999,1,4) $350 - $500,472.82,0,1,Surburban,0,Web,Mens E-Mail,0,0,0.0,3

In [57]:
df[df.recency < 7] = -100

In [58]:
df

,recency,history_segment,history,mens,womens,zip_code,newbie,channel,segment,visit,conversion,spend,DM_category
0,10,2) $100 - $200,142.44,1,0,Surburban,0,Phone,Womens E-Mail,0,0,0.0,4
1,-100,-100,-100.00,-100,-100,-100,-100,-100,-100,-100,-100,-100.0,-100
2,7,2) $100 - $200,180.65,0,1,Surburban,1,Web,Womens E-Mail,0,0,0.0,1
3,9,5) $500 - $750,675.83,1,0,Rural,1,Web,Mens E-Mail,0,0,0.0,2
4,-100,-100,-100.00,-100,-100,-100,-100,-100,-100,-100,-100,-100.0,-100
5,-100,-100,-100.00,-100,-100,-100,-100,-100,-100,-100,-100,-100.0,-100
6,9,3) $200 - $350,280.20,1,0,Surburban,1,Phone,Womens E-Mail,0,0,0.0,4
7,9,1) $0 - $100,46.42,0,1,Urban,0,Phone,Womens E-Mail,0,0,0.0,1
8,9,5) $500 - $750,675.07,1,1,Rural,1,Phone,Mens E-Mail,0,0,0.0,5
9,10,1) $0 - $100,32.84,0,1,Urban,1,Web,Womens E-Mail,0,0,0.0,1
10,7,5) $500 - $750,548.91,0,1,Urban,1,Phone,Womens E-Mail,1,0,0.0,1
11,-100,-100,-100.00,-100,-100,-100,-100,-100,-100,-100,-100,-100.0,-100
12,-100,-100,-100.00,-100,-100,-100,-100,-100,-100,-100,-100,-100.0,-100
13,-100,-100,-100.00,-100,-100,-100,-100,-100,-100,-100,-100,-100.0,-100
14,-100,-100,-100.00,-100,-100,-100,-100,-100,-100,-100,-100,-100.0,-100
15,-100,-100,-100.00,-100,-100,-100,-100,-100,-100,-100,-100,-100.0,-100
16,-100,-100,-100.00,-100,-100,-100,-100,-100,-100,-100,-100,-100.0,-100
17,9,2) $100 - $200,112.35,1,0,Rural,0,Web,Mens E-Mail,0,0,0.0,2
18,11,3) $200 - $350,219.04,1,1,Surburban,0,Phone,Mens E-Mail,0,0,0.0,5
19,-100,-100,-100.00,-100,-100,-100,-100,-100,-100,-100,-100,-100.0,-100
20,9,1) $0 - $100,29.99,0,1,Surburban,1,Phone,No E-Mail,0,0,0.0,5
21,11,2) $100 - $200,182.32,1,0,Surburban,0,Phone,Mens E-Mail,0,0,0.0,2
22,-100,-100,-100.00,-100,-100,-100,-100,-100,-100,-100,-100,-100.0,-100
23,-100,-100,-100.00,-100,-100,-100,-100,-100,-100,-100,-100,-100.0,-100
24,-100,-100,-100.00,-100,-100,-100,-100,-100,-100,-100,-100,-100.0,-100
25,-100,-100,-100.00,-100,-100,-100,-100,-100,-100,-100,-100,-100.0,-100
26,12,2) $100 - $200,115.39,0,1,Surburban,0,Phone,Mens E-Mail,1,0,0.0,3
27,-100,-100,-100.00,-100,-100,-100,-100,-100,-100,-100,-100,-100.0,-100
28,7,4) $350 - $500,435.73,0,1,Urban,1,Web,No E-Mail,0,0,0.0,5
29,-100,-100,-100.00,-100,-100,-100,-100,-100,-100,-100,-100,-100.0,-100
...,...,...,...,...,...,...,...,...,...,...,...,...,...
63970,-100,-100,-100.00,-100,-100,-100,-100,-100,-100,-100,-100,-100.0,-100
63971,-100,-100,-100.00,-100,-100,-100,-100,-100,-100,-100,-100,-100.0,-100
63972,-100,-100,-100.00,-100,-100,-100,-100,-100,-100,-100,-100,-100.0,-100
63973,8,4) $350 - $500,471.80,1,0,Surburban,1,Multichannel,Womens E-Mail,0,0,0.0,4
63974,8,1) $0 - $100,73.65,0,1,Surburban,0,Phone,Mens E-Mail,0,0,0.0,3
63975,10,"6) $750 - $1,000",883.92,1,0,Urban,1,Phone,No E-Mail,0,0,0.0,6
63976,-100,-100,-100.00,-100,-100,-100,-100,-100,-100,-100,-100,-100.0,-100
63977,8,1) $0 - $100,29.99,0,1,Surburban,0,Web,No E-Mail,1,0,0.0,5
63978,10,2) $100 - $200,102.01,0,1,Urban,1,Phone,Mens E-Mail,0,0,0.0,3
63979,10,2) $100 - $200,168.21,0,1,Surburban,0,Phone,No E-Mail,0,0,0.0,5
63980,-100,-100,-100.00,-100,-100,-100,-100,-100,-100,-100,-100,-100.0,-100
63981,-100,-100,-100.00,-100,-100,-100,-100,-100,-100,-100,-100,-100.0,-100
63982,-100,-100,-100.00,-100,-100,-100,-100,-100,-100,-100,-100,-100.0,-100
63983,-100,-100,-100.00,-100,-100,-100,-100,-100,-100,-100,-100,-100.0,-100
63984,-100,-100,-100.00,-100,-100,-100,-100,-100,-100,-100,-100,-100.0,-100
63985,9,1) $0 - $100,29.99,1,0,Urban,0,Phone,Mens E-Mail,1,0,0.0,2
63986,9,1) $0 - $100,35.26,0,1,Urban,1,Web,Womens E-Mail,0,0,0.0,1
63987,-100,-100,-100.00,-100,-100,-100,-100,-100,-100,-100,-100,-100.0,-100
63988,-100,-100,-100.00,-100,-100,-100,-100,-100,-100,-100,-100,-100.0,-100
63989,10,3) $200 - $350,304.30,1,1,Surburban,0,Web,Womens E-Mail,1,0,0.0,5
63990,-100,-100,-100.00,-100,-100,-100,-100,-100,-100,-100,-100,-100.0,-100
63991,-100,-100,-100.00,-100,-100,-100,-100,-100,-100,-100,-100,-100.0,-100
63992,-100,-100,-100.00,-100,-100,-100,-100,-100,-100,-100,-100,-100.0,-100
63993,-100,-100,-100.00,-100,-100,-100,-100,-100,-100,-100,-100,-100.0,-100
63994,7,1) $0 - $100,86.46,0,1,Urban,0,Web,Mens E-Mail,0,0,0.0,3
63995,10,2) $100 - $200,105.54,1,0,Urban,0,Web,Mens E-Mail,0,0,0.0,2
63996,-100,-100,-100.00,-100,-100,-100,-100,-100,-100,-100,-100,-100.0,-100
63997,-100,-100,-100.00,-100,-100,-100,-100,-100,-100,-100,-100,-100.0,-100
63998,-100,-100,-100.00,-100,-100,-100,-100,-100,-100,-100,-100,-100.0,-100
63999,-100,-100,-100.00,-100,-100,-100,-100,-100,-100,-100,-100,-100.0,-100

# Feature Representation
([lecture](https://courses.edx.org/courses/course-v1:Microsoft+DAT210x+4T2017/courseware/b7aa9093-0ee1-9e62-4188-6f9d25a2ce85/ce1c9548-56c6-5421-5541-94aec8434947/?activate_block_id=block-v1%3AMicrosoft%2BDAT210x%2B4T2017%2Btype%40sequential%2Bblock%40ce1c9548-56c6-5421-5541-94aec8434947))

In [62]:
import pandas as pd

In [63]:
ordered_satisfaction = ['Very Unhappy', 'Unhappy', 'Neutral', 'Happy', 'Very Happy']
df = pd.DataFrame({'satisfaction': ['Mad', 'Happy', 'Unhappy', 'Neutral']})
df

  satisfaction
0          Mad
1        Happy
2      Unhappy
3      Neutral

In [65]:
df['satisfaction2'] = df.satisfaction.astype(dtype='category',
                                            ordered = True,
                                            categories = ordered_satisfaction
                                            )

In [66]:
df

  satisfaction satisfaction2
0          Mad           NaN
1        Happy         Happy
2      Unhappy       Unhappy
3      Neutral       Neutral

Note that the undefined (in ordered_satisfaction) value, 'Mad' created a NaN in the satisfaction2 column.

In [67]:
df.dtypes

satisfaction       object
satisfaction2    category
dtype: object

Pandas implements a category as regular Python list.

Convert to numeric fashion, with the category codes from the index in ordered_satisfaction.

In [68]:
df.satisfaction2 = df.satisfaction2.cat.codes
df.satisfaction2

0   -1
1    3
2    1
3    2
Name: satisfaction2, dtype: int8

In [69]:
df

  satisfaction  satisfaction2
0          Mad             -1
1        Happy              3
2      Unhappy              1
3      Neutral              2

Note the NaN value is encoded now as -1.

In [70]:
df = pd.DataFrame({
    'vertebrates': [
        'Bird',
        'Bird',
        'Mammal',
        'Fish',
        'Amphibian',
        'Reptile',
        'Mammal'
    ]
})
df

  vertebrates
0        Bird
1        Bird
2      Mammal
3        Fish
4   Amphibian
5     Reptile
6      Mammal

In [71]:
df['vertebrates2'] = df.vertebrates.astype("category").cat.codes
df

  vertebrates  vertebrates2
0        Bird             1
1        Bird             1
2      Mammal             3
3        Fish             2
4   Amphibian             0
5     Reptile             4
6      Mammal             3

(Can erroneously/systematically introduce data relationships. Here, e.g., it seems like a Bird is 2 integer value difference from a Mammal, even though this is just related to the Alphabetic sort used to set up the typed category codes.)

In [72]:
df2 = pd.get_dummies(df, columns=['vertebrates'])
df2

,vertebrates2,vertebrates_Amphibian,vertebrates_Bird,vertebrates_Fish,vertebrates_Mammal,vertebrates_Reptile
0,1,0,1,0,0,0
1,1,0,1,0,0,0
2,3,0,0,0,1,0
3,2,0,0,1,0,0
4,0,1,0,0,0,0
5,4,0,0,0,0,1
6,3,0,0,0,1,0

(This is potentially more nuanced because it doesn't introduce the implied relationship that using `.astype("category").cat.codes` did above. It takes up more "space" or more features, but avoids introducing implied relationships. Perhaps think twice for data sets that have **many** categorical features.)

# Feature Representation - Continued

In [74]:
from sklearn.feature_extraction.text import CountVectorizer

In [75]:
corpus = [
    "Authman ran faster than Harry because Authman is real and Harry is fictional.",
    "Authman and Harry ran faster then faster and faster.",
    "W00t."
]

In [76]:
bow = CountVectorizer()
X = bow.fit_transform(corpus) # Produces a Sparse Matrix
X

<3x12 sparse matrix of type '<class 'numpy.int64'>'
	with 17 stored elements in Compressed Sparse Row format>

In [77]:
bow.get_feature_names()

['and',
 'authman',
 'because',
 'faster',
 'fictional',
 'harry',
 'is',
 'ran',
 'real',
 'than',
 'then',
 'w00t']

In [78]:
X.toarray()

array([[1, 2, 1, 1, 1, 2, 2, 1, 1, 1, 0, 0],
       [2, 1, 0, 3, 0, 1, 0, 1, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=int64)

(Bag of Words method for featurizing text counts word frequency, binning text frequency content in a chunk of text.)

(Moving on to Image Features)

In [92]:
from scipy import misc

In [95]:
img = misc.imread('importance.png')
type(img)

AttributeError: module 'scipy.misc' has no attribute 'imread'

In [85]:
img.shape

NameError: name 'img' is not defined

In [ ]:
img.dtype

In [ ]:
img = img[::2, ::2]
img.shape